//
// Created by kniti on 23-10-2022.
//

#ifndef COMPETITIVE_PROGRAMMING_LINKEDLISTTEMPLATE_H
#define COMPETITIVE_PROGRAMMING_LINKEDLISTTEMPLATE_H


class LinkedListTemplate {

};


#endif //COMPETITIVE_PROGRAMMING_LINKEDLISTTEMPLATE_H
